displayName: Traefik Get Real IP
type: middleware
import: github.com/rauny-henrique/traefik-get-real-ip
iconPath: .assets/icon.png

summary: By retrieving the correct real IP from single or multiple different load balancers(eg.Cloudflare), this plugin effectively prevents IP spoofing.

testData:
  Proxy:
    - proxyHeadername: X-From-Cdn
      proxyHeadervalue: cdn1
      realIP: X-Forwarded-For
    - proxyHeadername: X-From-Cdn
      proxyHeadervalue: cdn2
      realIP: Client-Ip
    - proxyHeadername: X-From-Cdn
      proxyHeadervalue: cdn3
      realIP: Cf-Connecting-Ip
      overwriteXFF: true
      overwriteRA: true
    - proxyHeadername: "*"
      realIP: RemoteAddr